# Generated by Django 5.0.7 on 2024-12-28 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_friend", models.BooleanField(default=False)),
                ("added_at", models.DateTimeField(auto_now=True)),
                (
                    "friendship",
                    models.TextField(
                        choices=[
                            ("NF", "Not Friend"),
                            ("F", "Friend"),
                            ("B", "Blocked"),
                            ("P", "Pending"),
                        ],
                        default="Not Friend",
                    ),
                ),
                (
                    "incoming_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outgoing_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("outgoing_user", "incoming_user")},
            },
        ),
    ]
