# Generated by Django 5.0.7 on 2024-12-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="status",
        ),
    ]
